# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57313bba4d0e1e3168eb564fcfc64859ea994429b3f83149441eace0b37cf1c6e75a63d4dee04617916a43d09a7c38c7e48757fe6d09da37c138fefb803fce93

test:
  secret_key_base: a79eb77484a723fd9eb5b994dd840c230f5b73d4e75384df8fce05b7e50f33e337ee110e84977c9946d60ebd788fe569979f117bfc4bdc516eae68d5d9ecc6bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a79eb77484a723fd9eb5b994dd840c230f5b73d4e75384df8fce05b7e50f33e337ee110e84977c9946d60ebd788fe569979f117bfc4bdc516eae68d5d9ecc6bd
